[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
#test-requires = "pytest"
test-command = "python -m danmakuC {package}/tests/test_dm.bin 1>NULL"
